version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    revive:
      rules:
        - name: context-as-argument
        - name: var-naming
        - name: exported
        - name: package-comments
        - name: receiver-naming
        - name: indent-error-flow
    nolintlint:
      require-explanation: true
      require-specific: true
    staticcheck:
      checks:
        - all
        - -ST1003
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/api/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/api/
